apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support
  template:
    metadata:
      labels:
        app: support
    spec:
      containers:
        - name: support
          image: $IMAGE_TAG
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "200m"
            limits:
              cpu: "500m"
